services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - esh-app

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - esh-app

networks:
  esh-app:
    driver: bridge